###############################################################################
## 03-submit.conf  —  Submit node  (ws-0.fort.wow.dev)
###############################################################################

DAEMON_LIST = MASTER, SCHEDD

## Submit node caches user credentials locally so the schedd can forward
## them to the execute node's starter during run_as_owner job starts.
CREDD_CACHE_LOCALLY = True
